version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_PASSWORD
      - MYSQL_DATABASE=MYSQL_DBNAME
      - MYSQL_HOST=MYSQL_HOST
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./todo-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=MYSQL_USER
      - DB_PASSWORD=MYSQL_PASSWORD
      - DB_NAME=MYSQL_DBNAME
      - DB_PORT=MYSQL_PORT
    stdin_open: true
    tty: true

volumes: 
  db: